name: Daily CS2 Profit Run

on:
  schedule:
    - cron: '0 0 * * *'  
  workflow_dispatch:

jobs:
  run-profit-master:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run CS2ProfitMaster
        run: |
          python -m cs2tracker.CS2ProfitMaster

      - name: Commit changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add prices.csv price_cache.json || true  # Ignore if no changes
          git commit -m "Update prices.csv and price_cache.json from daily run" || true
          git push || true  # Push changes back to the repo
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}